// Deploys oracle + exchange (and a mock USDG on local), adds the eight markets,
// and writes site/js/deployments.js.
//   Local:  npx hardhat run scripts/deploy.js --network localhost
//   Other:  RPC_URL=… DEPLOYER_KEY=0x… COLLATERAL=0x<USDG> OWNER=0x… KEEPER=0x… NAME="Chain" EXPLORER=https://… \
//           npx hardhat run scripts/deploy.js --network custom
const fs = require("fs");
const path = require("path");
const { ethers, network } = require("hardhat");
const MARKETS = require("./markets");
const OUT = path.join(__dirname, "..", "site", "js", "deployments.js");

function read() {
  if (!fs.existsSync(OUT)) return {};
  const m = fs.readFileSync(OUT, "utf8").match(/=\s*(\{[\s\S]*\});?\s*$/);
  return m ? JSON.parse(m[1]) : {};
}

async function main() {
  const [deployer, ...others] = await ethers.getSigners();
  const { chainId } = await ethers.provider.getNetwork();
  const local = chainId === 31337n;
  const owner = process.env.OWNER || deployer.address;

  let collateral = process.env.COLLATERAL;
  if (!collateral) {
    if (!local) throw new Error("Set COLLATERAL to the USDG token address on this chain");
    const mock = await ethers.deployContract("MockUSDG");
    collateral = await mock.getAddress();
  }
  const token = await ethers.getContractAt("MockUSDG", collateral);
  const dec = await token.decimals();

  const oracle = await ethers.deployContract("PriceOracle", [deployer.address]);
  const ex = await ethers.deployContract("NightfallExchange", [deployer.address, collateral, await oracle.getAddress(), ethers.parseUnits("5", dec)]);
  const rc = await ex.deploymentTransaction().wait();
  for (const m of MARKETS) await (await ex.addMarket(m.symbol, 10)).wait();
  await (await oracle.setKeeper(process.env.KEEPER || deployer.address, true)).wait();

  if (local) {
    await (await oracle.push(MARKETS.map((_, i) => i), MARKETS.map((m) => ethers.parseUnits(String(m.seed), 8)))).wait();
    const lp = others[0];
    await (await token.mint(lp.address, ethers.parseUnits("250000", dec))).wait();
    await (await token.connect(lp).approve(await ex.getAddress(), ethers.MaxUint256)).wait();
    await (await ex.connect(lp).deposit(ethers.parseUnits("250000", dec))).wait();
    for (const s of others.slice(1, 6)) await (await token.mint(s.address, ethers.parseUnits("10000", dec))).wait();
  }
  if (owner.toLowerCase() !== deployer.address.toLowerCase()) {
    await (await ex.transferOwnership(owner)).wait();
    await (await oracle.transferOwnership(owner)).wait();
  }

  const all = read();
  all[String(chainId)] = {
    name: process.env.NAME || (local ? "Local node" : network.name),
    rpc: local ? "http://127.0.0.1:8545" : process.env.RPC_URL,
    explorer: process.env.EXPLORER || "",
    exchange: await ex.getAddress(),
    oracle: await oracle.getAddress(),
    collateral,
    startBlock: rc.blockNumber,
  };
  fs.writeFileSync(OUT, `// Generated by scripts/deploy.js\nwindow.LN_DEPLOYMENTS = ${JSON.stringify(all, null, 2)};\n`);
  console.log(`exchange ${await ex.getAddress()} oracle ${await oracle.getAddress()} collateral ${collateral} on ${chainId}`);
}
main().catch((e) => { console.error(e); process.exit(1); });
