// Deploys ForgeFactory and records its address in site/js/deployments.js.
//   npx hardhat run scripts/deploy.js --network localhost   (also seeds demo launches)
//   DEPLOYER_KEY=0x... TREASURY=0x... npx hardhat run scripts/deploy.js --network bittensorTestnet
const fs = require("fs");
const path = require("path");
const { ethers, network } = require("hardhat");

const OUT = path.join(__dirname, "..", "site", "js", "deployments.js");
const E = (n) => ethers.parseEther(String(n));

function readDeployments() {
  if (!fs.existsSync(OUT)) return {};
  const src = fs.readFileSync(OUT, "utf8");
  const m = src.match(/=\s*(\{[\s\S]*\});?\s*$/);
  return m ? JSON.parse(m[1]) : {};
}

async function main() {
  const [deployer, ...others] = await ethers.getSigners();
  const { chainId } = await ethers.provider.getNetwork();
  const owner = process.env.OWNER || deployer.address;
  const treasury = process.env.TREASURY || owner;
  const minLiq = E(process.env.MIN_LIQUIDITY || "0.1");

  const factory = await ethers.deployContract("ForgeFactory", [owner, treasury, minLiq]);
  await factory.waitForDeployment();
  const receipt = await factory.deploymentTransaction().wait();
  const address = await factory.getAddress();
  console.log(`ForgeFactory on ${network.name} (${chainId}): ${address}`);

  const all = readDeployments();
  all[String(chainId)] = { factory: address, startBlock: receipt.blockNumber };

  if (chainId === 31337n) await seed(factory, deployer, others);

  fs.writeFileSync(OUT, `// Generated by scripts/deploy.js\nwindow.TF_DEPLOYMENTS = ${JSON.stringify(all, null, 2)};\n`);
  console.log(`wrote ${path.relative(process.cwd(), OUT)}`);
}

async function seed(factory, deployer, others) {
  const alpha = await ethers.deployContract("MockAlpha", ["Wrapped SN10 Alpha", "wSN10"]);
  await factory.setQuoteAsset(await alpha.getAddress(), "SN10 · alpha", true, E(1));
  const far = Math.floor(Date.now() / 1000) + 1e7;

  const demos = [
    { name: "Lattice Agents", symbol: "LATT", sector: "agents", kind: "Subnet Coin", netuid: 20, liq: 25, desc: "A community coin for people who think autonomous agents are the next big workload on Bittensor." },
    { name: "Coldwire", symbol: "WIRE", sector: "inference", kind: "Token", liq: 8, desc: "Betting on cheap, fast, open inference." },
    { name: "Proof of Shard", symbol: "SHARD", sector: "data", kind: "Subnet Candidate", liq: 3, desc: "A candidate subnet for verifiable dataset curation. Building in the open." },
    { name: "Gridlock", symbol: "GRID", sector: "compute", kind: "Token", liq: 12, alpha: true, desc: "Compute-market conviction, paired with SN10 alpha." },
  ];
  for (let i = 0; i < demos.length; i++) {
    const d = demos[i];
    const creator = others[i] || deployer;
    const meta = JSON.stringify({ description: d.desc, sector: d.sector, kind: d.kind, netuid: d.netuid, website: "", x: "" });
    let tx;
    if (d.alpha) {
      await alpha.mint(creator.address, E(1000));
      await alpha.connect(creator).approve(await factory.getAddress(), E(d.liq));
      tx = await factory.connect(creator).createLaunch({ name: d.name, symbol: d.symbol, supply: E(1e9), metadata: meta, quote: await alpha.getAddress(), quoteAmount: E(d.liq) });
    } else {
      tx = await factory.connect(creator).createLaunch({ name: d.name, symbol: d.symbol, supply: E(1e9), metadata: meta, quote: ethers.ZeroAddress, quoteAmount: E(d.liq) }, { value: E(d.liq) });
    }
    await tx.wait();
  }
  // some trading history so charts have shape
  const launches = await factory.getLaunches(0, 10);
  for (const l of launches) {
    const pool = await ethers.getContractAt("ForgePool", l.pool);
    const token = await ethers.getContractAt("ForgeToken", l.token);
    for (let j = 0; j < 8; j++) {
      const trader = others[(j + 5) % others.length];
      if (l.quote === ethers.ZeroAddress) {
        await (await pool.connect(trader).buy(0, trader.address, far, { value: E((j % 3) + 0.5) })).wait();
      } else {
        const alphaC = alpha.connect(trader);
        await alpha.mint(trader.address, E(5));
        await (await alphaC.approve(l.pool, E(2))).wait();
        await (await pool.connect(trader).buyWithQuote(E(2), 0, trader.address, far)).wait();
      }
      if (j % 3 === 2) {
        const bal = (await token.balanceOf(trader.address)) / 3n;
        await (await token.connect(trader).approve(l.pool, bal)).wait();
        await (await pool.connect(trader).sell(bal, 0, trader.address, far)).wait();
      }
    }
  }
  console.log(`seeded ${launches.length} demo launches (mock alpha ${await alpha.getAddress()})`);
}

main().catch((e) => { console.error(e); process.exit(1); });
